language: groovy
jdk:
- oraclejdk8
sudo: false
script: "./travis-build.sh"
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.m2/"
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
env:
  global:
  - secure: qnF2K7JZLLDPJ3oveG1b7bs5/cLYzxnc9T0kuyqwL1RRXXNKWdS6jJ+bEe1shE3kG4IVI638IUP67K04ltmGhGHYbFW4hL20TTaeMgXhDr2haWCRhfRoS+F5cfexpI7PPOSYKatMjUd8JeQZinZXSHewU23fVsJKPGYe2ifcxo1e1tzU09eGB4OmmIB6f5xBHD9YXatRcmMS8xMXizFGigXkHrqaHKYRr/tlJrh2h0+dUO7y8vaSs1SSGaRgTl8DZj84X2aB8Wns3cjhXqmHg41JT1+3BYaK5ygnfWBFsNuCt4vK46Y1VlwACLup6n3rnBzqh0N2bsXRT0BWvZLtYVoczslfEqyVqcaL0/FM1AMBfH/CLHvHXLAtZ6eTGTkA0ySvTzC/VmoFJuLhWesQhiroLXpyNh7P5YgzKpkFFDgkTdbB4On+DWi4S4lTeNUGPN9V2Bpd6zvSdIUdS26XVKAsSTkE8/vO+AA52zGCFXsS0ALd4nw6f2geF1AyxreQgMfEHBox52jEEuwjHvWZnmQFihH5RXwaBUrhC4OBCVWYgikXcjpbGmktlFjGin+vjz3HHd7ZafZaBgCZ7rQaoKlJk4ngpICmifhHtC8cx9cEPnMGSA6d/+DYNeTBkzq+pB68YYm9r1s8T9ALSgaOwNflz1LS8omm0PXB/7gg914=
  - secure: EHdDYEvqRTEjrLdCOYVpnSGuln90dOj7lezTDpuOZl5yNYucnGnbDW41dFbb794fbY1N9q/PT6flQhIx3pZqxbsdLwbW15bkyYeiqDiWoG4yEIyoCT3+w/sRRnQ3JAFxM5O6gURD9L1OAzaW6q2zLIqlOPk3beWFJFBHl9rJlwuIGgHutUd5PUPyIWyqZ1oP6J4FHIfyYW6yJn+QYeYcIwq7BMJNDw4rszInwxcrbH7v1rxpz2tcQ+7oJCuNK2ojfG9zDa0wPFBAx0q1ak85hRaDTOgq2MU3M+5yEp+UabW28QbFbgzExkxXUHzBycjQjIXRVlSAi5bZ3ul7203JMqSGRoYCWoAql/nTu/7HZYGSSnezNmLJEZQXddZNI4Xp7357iINOO3rPlO+ZnKba6BHjTR3/nP8d9bWwDhAXYthq3DFXXF1z59qO4uCvyzK2kgTNEroyPnu1hur3wTOCW6jjRKssqYEDYRbWIcqwNPBLwDwuilG2fvAzDD5G0Opl0OTuQd48KKgll5RMtyWE+UwkuEOjAdofaFVpuG0G7uJlHVuvjM60Dz476DldUQKbW5nKbhGvmCvyNDLefRIWebeSN2T6C5hWrBm1Zmph+Gj78m8UUEi139FwxFY1bUEZg3oDjq7KXV5iVBVFkfqy21j7uSCjkYBCWHXIubgMOjs=
